### ISSUE TITLE
Error on launch.

### ISSUE THREAD

**Issue by MaximumWoahverdrive** [thebarbershopper/bombly#18]
I'm getting the following output when trying to run the dfly-loader-wsr.py
```
Traceback (most recent call last):
  File "dfly-loader-wsr.py", line 21, in <module>
    import pythoncom
  File "C:\Python27\lib\site-packages\pywin32-224-py2.7-win32.egg\pythoncom.py", line 2, in <module>
    import pywintypes
ImportError: No module named pywintypes
```
I am using Python version 2.7.15
and have installed pypiwin32 using ```pip install pypiwin32```

**Comment by sylvexite** [comment]
Having the same problem, using Python version 2.7.15
Also installed pypiwin32 using the same command as OP.

**Comment by Jamifa** [comment]
I know this thread is pretty old, but..  I was able to get it to work after some fiddling.

I have Python 2.7.2 32-bit
Downloaded and installed addons from here: https://github.com/mhammond/pywin32/releases

Make sure you get the right addons for the Python version you're using (you may need to uninstall your current version of python just to make sure - or just change the default version)

Followed the readme instructions from there and it worked.
